language: php

php:
    - 5.6
    - 7.0
    
script:
    - ./vendor/bin/grumphp run
    
env:
    - SYMFONY_VERSION="^2.8"
    - SYMFONY_VERSION="^3.1"

install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/framework-bundle:${SYMFONY_VERSION}" --no-update; fi;
    - composer update


